"""Update Person schema

Revision ID: 4255bfd94db6
Revises: 
Create Date: 2024-08-08 04:07:10.981095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4255bfd94db6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('anniversaries', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dislikes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminders', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('how_we_met', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('favorite_memory', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recent_updates', sa.Text(), nullable=True))
        batch_op.drop_column('interests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', mysql.TEXT(), nullable=True))
        batch_op.drop_column('recent_updates')
        batch_op.drop_column('favorite_memory')
        batch_op.drop_column('how_we_met')
        batch_op.drop_column('reminders')
        batch_op.drop_column('dislikes')
        batch_op.drop_column('likes')
        batch_op.drop_column('anniversaries')
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###
