"""Add more fields to Person model

Revision ID: a05641cbc560
Revises: 
Create Date: 2024-08-08 08:42:10.461174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a05641cbc560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('anniversary_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('anniversary_date', sa.Date(), nullable=True))
        batch_op.drop_column('anniversaries')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anniversaries', sa.DATE(), nullable=True))
        batch_op.drop_column('anniversary_date')
        batch_op.drop_column('anniversary_title')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###

