"""Initial migration with updated Person model

Revision ID: c95c87a6e8cb
Revises: 
Create Date: 2024-08-07 23:16:36.122741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95c87a6e8cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminders', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('how_we_met', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('favorite_memory', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recent_updates', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.drop_column('recent_updates')
        batch_op.drop_column('favorite_memory')
        batch_op.drop_column('how_we_met')
        batch_op.drop_column('reminders')

    # ### end Alembic commands ###
